# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ImageNTuple": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://ababino.github.io/fastpapers/"

git_url = "https://github.com/ababino/fastpapers/tree/master/"

def custom_doc_links(name): return None
