# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"explode_types": "00_core.ipynb",
         "explode_lens": "00_core.ipynb",
         "explode_shapes": "00_core.ipynb",
         "explode_ranges": "00_core.ipynb",
         "ImageNTuple": "00_core.ipynb",
         "ImageTupleBlock": "00_core.ipynb",
         "ConditionalGenerator": "00_core.ipynb",
         "SiameseCritic": "00_core.ipynb",
         "GenMetric": "00_core.ipynb",
         "CriticMetric": "00_core.ipynb",
         "l1": "00_core.ipynb",
         "GANLearner.show_results": "00_core.ipynb",
         "URLs.FACADES": "00_core.ipynb",
         "URLs.FACADES_BASE": "00_core.ipynb",
         "URLs.FACADES_EXTENDED": "00_core.ipynb",
         "URLs.CELEBA": "00_core.ipynb",
         "download_file_from_google_drive": "00_core.ipynb",
         "save_response_content": "00_core.ipynb",
         "FID_WEIGHTS_URL": "00_core.ipynb",
         "gen_bce_l1_loss": "01_isola2017image.ipynb",
         "crit_bce_loss": "01_isola2017image.ipynb",
         "Inception": "02_heusel2017gans.ipynb",
         "FIDMetric": "02_heusel2017gans.ipynb"}

modules = ["core.py",
           "isola2017image.py",
           "heusel2017gans.py"]

doc_url = "https://ababino.github.io/fastpapers/"

git_url = "https://github.com/ababino/fastpapers/tree/master/"

def custom_doc_links(name): return None
