# AUTOGENERATED! DO NOT EDIT! File to edit: 01_isola2017image.ipynb (unless otherwise specified).

__all__ = ['gen_bce_l1_loss', 'crit_bce_loss']

# Cell
from .core import *
from fastai.data.external import untar_data, URLs
from fastai.data.transforms import get_image_files
from fastai.data import *
from fastai.basics import *
from fastai.vision.data import *
from fastai.vision.core import *
from fastcore.all import *
from fastai.vision.augment import *
from fastai.vision.gan import *

# Cell
def gen_bce_l1_loss(fake_pred, output, target, l1_weight=100):
    l1_loss = nn.L1Loss()(output[-1],target[-1])
    ones = fake_pred.new_ones(*fake_pred.shape)
    bce_loss = nn.BCEWithLogitsLoss()(fake_pred, ones)
    return bce_loss + l1_weight*l1_loss

# Cell
def crit_bce_loss(real_pred, fake_pred):
    ones  = real_pred.new_ones(*real_pred.shape)
    zeros = fake_pred.new_zeros(*fake_pred.shape)
    loss_neg = nn.BCEWithLogitsLoss()(fake_pred, zeros)
    loss_pos = nn.BCEWithLogitsLoss()(real_pred, ones)
    return (loss_neg+ loss_pos)/2